
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 00:56:00 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 12;
  public static final int LBRACKET = 14;
  public static final int CHAR = 45;
  public static final int CONST = 40;
  public static final int LPAREN = 16;
  public static final int SEMI = 25;
  public static final int CONTINUE = 33;
  public static final int MINUS = 6;
  public static final int RPAREN = 17;
  public static final int AND = 19;
  public static final int LT = 11;
  public static final int OR = 20;
  public static final int BOOL = 44;
  public static final int COMMA = 21;
  public static final int CLASS = 38;
  public static final int INC = 23;
  public static final int DIV = 3;
  public static final int PLUS = 5;
  public static final int ASSIGN = 22;
  public static final int IF = 28;
  public static final int DOT = 13;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int RBRACKET = 15;
  public static final int EQUAL = 7;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 2;
  public static final int NUMBER = 42;
  public static final int MOD = 4;
  public static final int IDENT = 43;
  public static final int BREAK = 31;
  public static final int VOID = 37;
  public static final int GTE = 10;
  public static final int LBRACE = 26;
  public static final int ELSE = 32;
  public static final int READ = 36;
  public static final int WHILE = 30;
  public static final int RBRACE = 27;
  public static final int EXTENDS = 41;
  public static final int PROG = 39;
  public static final int DIFF = 8;
  public static final int DEC = 24;
  public static final int GT = 9;
  public static final int PRINT = 35;
  public static final int DO = 29;
}

